---

- name: Get bot codes
  git:
    repo: https://github.com/tparsa/photoeditorbot.git
    dest: ~/photo-editor-bot
    force: true

- name: replace ir.archives with archive
  replace:
    path: /etc/apt/sources.list
    regexp: 'https://ir.'
    replace: 'https://'
  become: true

- name: Add python repository
  apt_repository:
    repo: ppa:fkrull/deadsnakes
    state: present
  become: true
  ignore_errors: true

# - name: Fix Unknown apt_pkg problem
#   copy:
#     src: /usr/lib/python3/dist-packages/apt_pkg.cpython-34m-x86_64-linux-gnu.so
#     dest: /usr/lib/python3/dist-packages/apt_pkg.so
#     remote_src: yes
#   become: true

# - name: Install python3-apt
#   apt:
#     name: python3-apt
#     state: latest
#   become: true

- name: apt update
  apt:
    update_cache: yes
  become: true

- name: install python apt requirements
  apt:
    name: "{{ python_apt_packages }}"
    state: present
  become: true

- name: Install postgresql requirements
  apt:
    name: "{{ postgres_apt_packages }}"
    state: present
  become: true

- name: Change python to python3.6
  shell:
    cmd: 'update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1'
  become: true

- name: Install python pip requirements
  pip:
    requirements: ~/photo-editor-bot/requirements.txt

- name: Alter postgres user to add password
  postgresql_user:
    name: postgres
    password: 342|Klw,QSzk+
  become: true
  become_user: postgres

- name: Create databse
  postgresql_db:
    name: coloring_bot_db
    login_password: 342|Klw,QSzk+
  become: true
  become_user: postgres

- name: Create users table
  postgresql_table:
    login_password: 342|Klw,QSzk+
    db: coloring_bot_db
    name: users
    columns:
    - id bigserial primary key
    - chat_id text
    - edits_left int
    - credit_code text
    - credit_code_effect int
  become: true
  become_user: postgres