python_apt_packages:
  - python3.6
  - python3.6-dev
  - python3-pip
  - python3-setuptools
  - python3-apt

postgres_apt_packages:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
  - libpq-dev
